=== frank71336/Mrv.Regatta.Waage/Xml/regeln.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns="" id="User" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:include schemaLocation="renninfo.xsd" />
  <xs:element name="Regeln">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element minOccurs="0" maxOccurs="unbounded" name="Regel" type="CT_Regel" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="CT_Regel">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="unbounded" name="If" type="CT_Bedingung" />
      <xs:element minOccurs="0" maxOccurs="unbounded" name="IfNot" type="CT_Bedingung" />
      <xs:element minOccurs="1" maxOccurs="1" name="RennInfo" type="CT_RennInfo" />
    </xs:sequence>
    <xs:attribute name="Aktiv" type="xs:boolean" use="required" />
  </xs:complexType>
  <xs:complexType name="CT_Bedingung">
    <xs:attribute name="RegEx" type="xs:string" use="required" />
  </xs:complexType>
</xs:schema>

=== frank71336/Mrv.Regatta.Waage/data/data/regeln.xml
<?xml version="1.0" encoding="utf-8"?>
<Regeln xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/DATEN/Programmierung/C%23/Mrv.Regatta.Waage/Xml/regeln.xsd">
 
  <!-- Kinder Jungen -->
  
  <Regel Aktiv="true">
	<!-- Regel muss zuerst kommen, damit nicht eine der anderen Regeln unten zuschlägt! -->
    <If RegEx="Jung [^1]x 12 u\. 13.*LG" />
    <RennInfo Einzelgewicht="50.0" Durchschnittsgewicht="50.0" Kinderrennen="true" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="Jung 1x 12.*LG" />
    <RennInfo Einzelgewicht="45.0" Kinderrennen="true" />
  </Regel>
     
  <Regel Aktiv="true">
    <If RegEx="Jung [^1]x 12.*LG" />
    <RennInfo Einzelgewicht="45.0" Durchschnittsgewicht="45.0" Kinderrennen="true" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="Jung 1x 13.*LG" />
    <RennInfo Einzelgewicht="50.0" Kinderrennen="true" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="Jung [^1]x 13.*LG" />
    <RennInfo Einzelgewicht="50.0" Durchschnittsgewicht="50.0" Kinderrennen="true" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="Jung 1x 14.*LG" />
    <RennInfo Einzelgewicht="55.0" Kinderrennen="true" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="Jung [^1]x 14.*LG" />
    <RennInfo Einzelgewicht="55.0" Durchschnittsgewicht="55.0" Kinderrennen="true" />
  </Regel>
  
  <!-- Kinder Mädchen -->
  
  <Regel Aktiv="true">
    <If RegEx="Mäd 1x 12.*LG" />
    <RennInfo Einzelgewicht="45.0" Kinderrennen="true" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="Mäd [^1]x 12.*LG" />
    <RennInfo Einzelgewicht="45.0" Durchschnittsgewicht="45.0" Kinderrennen="true" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="Mäd 1x 13.*LG" />
    <RennInfo Einzelgewicht="50.0" Kinderrennen="true" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="Mäd [^1]x 13.*LG" />
    <RennInfo Einzelgewicht="50.0" Durchschnittsgewicht="50.0" Kinderrennen="true" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="Mäd 1x 14.*LG" />
    <RennInfo Einzelgewicht="52.5" Kinderrennen="true" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="Mäd [^1]x 14.*LG" />
    <RennInfo Einzelgewicht="52.5" Durchschnittsgewicht="52.5" Kinderrennen="true" />
  </Regel>

  <!-- Junioren Männer -->
  
  <Regel Aktiv="true">
    <If RegEx="JM 1x A .*LG" />
    <RennInfo Einzelgewicht="67.5" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="JM [^1]x A .*LG" />
    <RennInfo Einzelgewicht="67.5" Durchschnittsgewicht="65.0" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="JM 1x B .*LG" />
    <RennInfo Einzelgewicht="65.0" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="JM [^1]x\+ B .*LG" />
    <RennInfo Einzelgewicht="65.0" Durchschnittsgewicht="62.5" GewichtSteuermann="55.0" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="JM [^1]x B .*LG" />
    <RennInfo Einzelgewicht="65.0" Durchschnittsgewicht="62.5" />
  </Regel>
  
  <!-- Junioren Frauen -->
  
  <Regel Aktiv="true">
    <If RegEx="JF 1x A .*LG" />
    <RennInfo Einzelgewicht="57.5" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="JF [^1]x A .*LG" />
    <RennInfo Einzelgewicht="57.5" Durchschnittsgewicht="55.0" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="JF 1x B .*LG" />
    <RennInfo Einzelgewicht="55.0" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="JF [^1]x B .*LG" />
    <RennInfo Einzelgewicht="55.0" Durchschnittsgewicht="52.5" />
  </Regel>
  
  <!-- Schwere Männer -->
  
  <Regel Aktiv="true">
    <If RegEx="SM 1x.*LG" />
    <RennInfo Einzelgewicht="72.5" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="SM [^1]x.*LG" />
    <RennInfo Einzelgewicht="72.5" Durchschnittsgewicht="70.0" />
  </Regel>
  
  <!-- Schwere Frauen -->
  
  <Regel Aktiv="true">
    <If RegEx="SF 1x.*LG" />
    <RennInfo Einzelgewicht="59.0" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="SF [^1]x.*LG" />
    <RennInfo Einzelgewicht="59.0" Durchschnittsgewicht="57.0" />
  </Regel>
  
  <!-- Gesteuerte Rennen (keine LG-Rennen!!!, keine Kinderrennen! ) -->
  
  <Regel Aktiv="true">
    <If RegEx="JM.*\+" />
    <RennInfo GewichtSteuermann="55.0" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="SM.*\+" />
    <RennInfo GewichtSteuermann="55.0" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="MM.*\+" />
    <RennInfo GewichtSteuermann="55.0" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="JF.*\+" />
    <RennInfo GewichtSteuermann="50.0" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="JF.*\+" />
    <RennInfo GewichtSteuermann="50.0" />
  </Regel>
  
  <Regel Aktiv="true">
    <If RegEx="SF.*\+" />
    <RennInfo GewichtSteuermann="50.0" />
  </Regel>
   
</Regeln>
